name: BUILDBOT
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 64-bit
            os: windows-latest
            spec: src/build.spec
            artifact: Elden_Ring_Save_Editor_WIN64
            artifact-path: dist/
          - name: Windows 32-bit
            os: windows-latest
            spec: src/build_win32.spec
            artifact: Elden_Ring_Save_Editor_WIN32
            artifact-path: dist/Elden_Ring_Save_Editor_WIN32.exe
            uv-python: cpython-3.14-windows-i686
          - name: Linux x86_64
            os: ubuntu-latest
            spec: src/build.spec
            artifact: Elden_Ring_Save_Editor_LINUX_x86_64
            artifact-path: dist/
          - name: macOS Silicon
            os: macos-latest
            spec: src/build_mac.spec
            artifact: Elden_Ring_Save_Editor_MAC-Silicon
            artifact-path: dist/*.app
          - name: macOS Intel
            os: macos-15-intel
            spec: src/build_mac.spec
            artifact: Elden_Ring_Save_Editor_MAC-Intel
            artifact-path: dist/*.app
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Setup MSVC for Win32
        if: matrix.name == 'Windows 32-bit'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Install Dependencies
        run: uv sync ${{ matrix.uv-python && format('--python {0}', matrix.uv-python) || '' }}
      - name: Build Executable
        run: uv run pyinstaller ${{ matrix.spec }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact-path }}
